version: '3.8'
services:
  gateway:
    build: .
    restart: always
    hostname: gateway
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: yarn run start:debug 

