export const Locations = [
  {
    name: 'All Cities',
    value: 'all',
  },
  {
    name: 'Ho Chi Minh',
    value: 'HCM',
  },
  {
    name: 'Ha Noi',
    value: 'HN',
  },
  {
    name: 'Da Nang',
    value: 'DN',
  },
  {
    name: 'Other',
    value: 'other',
  },
];

export const JobSkills = [
  'Html',
  'Javascript',
  'NodeJs',
  'NextJs',
  'Nests',
  'Android',
  'C',
  'C++',
  '.NET',
  'IOS',
  'MongoDB',
  'MySQL',
  'Cansandra',
  'VueJS',
  'NuxtJS',
  'Linux',
  'AWS',
  'Firebase',
  'UI-UX',
  'OOP',
  'MVC',
  'Oracle',
  'Django',
  'Ruby',
  'Ruby on Rails',
  'Agile',
  'Angular',
  'AngularJS',
  'ASP.NET',
  'AWS',
  'Blockchain',
  'Bridge Engineer',
  'Business Analyst',
  'C#',
  'C++',
  'C language',
  'Cloud',
  'CSS',
  'Database',
  'Designer',
  'DevOps',
  'Django',
  'Drupal',
  'Embedded',
  'English',
  'ERP',
  'Games',
  'Golang',
  'HTML5',
  'Hybrid',
  'iOS',
  'IT Support',
  'J2EE',
  'Japanese',
  'Java',
  'JavaScript',
  'JQuery',
  'JSON',
  'Kotlin',
  'Laravel',
  'Linux',
  'Magento',
  'Manager',
  'MVC',
  'MySQL',
  '.NET',
  'Networking',
  'NoSQL',
  'Objective C',
  'OOP',
  'Oracle',
  'PHP',
  'PostgreSql',
  'Product Manager',
  'Project Manager',
  'Python',
  'QA QC',
  'ReactJS',
  'React Native',
  'Ruby',
  'Ruby on Rails',
  'SAP',
  'Scala',
  'Sharepoint',
  'Software Architect',
  'Spring',
  'SQL',
  'Swift',
  'System Admin',
  'System Engineer',
  'Team Leader',
  'Tester',
  'UI-UX',
  'Unity',
  'VueJS',
  'Wordpress',
  'Xamarin',
];

export const JobTitles = [
  '.NET Developer',
  'Android App Developer',
  'Android Developer',
  'Back End Developer',
  'Back End Web Developer',
  'Bridge Engineer',
  'Business Analyst',
  'C++ Developer',
  'Embedded Engineer',
  'Front End Developer',
  'Front End Web Developer',
  'Full Stack Developer',
  'Full Stack Web Developer',
  'Java Developer',
  'Java Web Developer',
  'Mobile Apps Developer',
  'NodeJS Developer',
  'PHP Developer',
  'Product Manager',
  'Product Owner',
  'Project Manager',
  'Python Developer',
  'Python Web Developer',
  'Senior Back End Developer',
  'Senior Front End Developer',
  'Senior Full Stack Developer',
  'Senior Full Stack Web Developer',
  'Senior Java Developer',
  'Senior Mobile Apps Developer',
  'Senior Product Owner',
  'Software Architect',
  'Software Developer',
  'System Administrator',
  'System Engineer',
  'Team Leader',
  'Tester',
  'UX UI Designer',
  'iOS Developer',
];
